name: CI-PROD

env:
  S3_BUCKET: "stellar-webapp"
  DISTRIBUTION_ID: "E3OCVFWLLR8YMG"
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: aws s3 sync ./dist s3://${{ env.S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete
      - run: aws s3 cp ./dist/index.html s3://${{ env.S3_BUCKET }}/index.html --no-progress --acl public-read --cache-control no-cache
  invalidate-cache:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID }} --paths "/*"
